name: Build and Push Docker Image
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
 
    - name: Restore dependencies
      run: dotnet restore DockerizedWebApp/DockerizedWebApp.csproj
 
    - name: Build project
      run: dotnet build DockerizedWebApp/DockerizedWebApp.csproj --configuration Release
 
    - name: Run tests (if applicable)
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true